CREATE SEQUENCE SEQ_MOVIMENTACAO;
CREATE TABLE MOVIMENTACAOESTOQUE (
	MOVIMENTACAOESTOQUEID NUMERIC(20) NOT NULL,
	TIPO VARCHAR(20) NOT NULL,
	DATA DATE,
	
		
	CONSTRAINT PK_MOVIMENTACAOESTOQUE PRIMARY KEY (MOVIMENTACAOESTOQUEID)
);