CREATE SEQUENCE SEQ_FORNECEDORTELEFONE;
CREATE TABLE FORNECEDORTELEFONE (
	FORNECEDORTELEFONEID NUMERIC(20) NOT NULL,
	FORNECEDORID NUMERIC(20),
	TIPO VARCHAR(50),
	NUMERO VARCHAR(11),
	CONSTRAINT PK_FORNECEDORTELEFONE PRIMARY KEY (FORNECEDORTELEFONEID),
	CONSTRAINT FK_FORNECEDORTELEFONE1 FOREIGN KEY (FORNECEDORID) REFERENCES FORNECEDOR (FORNECEDORID)
);