CREATE SEQUENCE SEQ_FORNECEDOR;
CREATE TABLE FORNECEDOR (
	FORNECEDORID NUMERIC(20) NOT NULL,
	RAZAOSOCIAL VARCHAR(300),
	NOMEFANTASIA VARCHAR(300),
	CPF VARCHAR(11),
	CNPJ VARCHAR(14),
	
	MUNICIPIODOFORNECEDORID NUMERIC(20),
	
	CONSTRAINT PK_FORNECEDOR PRIMARY KEY (FORNECEDORID),
	CONSTRAINT FK_FORNECEDOR1 FOREIGN KEY (MUNICIPIODOFORNECEDORID) REFERENCES MUNICIPIO (MUNICIPIOID)
);