CREATE SEQUENCE SEQ_UNIDADEMEDIDA;
CREATE TABLE UNIDADEMEDIDA (
	UNIDADEMEDIDAID NUMERIC(20) NOT NULL,
	NOME VARCHAR(300) NOT NULL,
	SITUACAO VARCHAR(10),
	CONSTRAINT PK_UNIDADEMEDIDA PRIMARY KEY (UNIDADEMEDIDAID)
);