CREATE SEQUENCE SEQ_ITEMSAIDA;
CREATE TABLE ITEMSAIDA (
	ITEMSAIDAID NUMERIC(20) NOT NULL,
	MOVIMENTACAOESTOQUEID NUMERIC(20) NOT NULL,
	PRODUTOID NUMERIC(20),
	QUANTIDADE NUMERIC(8),
	VALORVENDA NUMERIC(8,2),
	
	CONSTRAINT PK_ITEMSAIDA PRIMARY KEY (ITEMSAIDAID),
	CONSTRAINT FK_ITEMSAIDA1 FOREIGN KEY (MOVIMENTACAOESTOQUEID) REFERENCES MOVIMENTACAOESTOQUE (MOVIMENTACAOESTOQUEID),
	CONSTRAINT FK_ITEMSAIDA2 FOREIGN KEY (PRODUTOID) REFERENCES PRODUTO (PRODUTOID)
);