ALTER TABLE PRODUTO
	ADD MARCA VARCHAR(300) NOT NULL,
	ADD UNIDADE VARCHAR(300) NOT NULL,
	ADD ESTOQUE_MINIMO INTEGER,
	ADD VALOR_VENDA NUMERIC (8,2) NOT NULL,
	ADD VALOR_CUSTO NUMERIC (8,2),
	ADD SITUACAO VARCHAR(10)
