CREATE SEQUENCE SEQ_ITENSENTRADA;
CREATE TABLE ITENSENTRADA (
	ITENSENTRADAID NUMERIC(20) NOT NULL,
	ENTRADAPRODUTOID NUMERIC(20) NOT NULL,
	PRODUTOID NUMERIC(20),
	QUANTIDADE NUMERIC(8),
	VALORCUSTO NUMERIC(8,2),
	VALORVENDA NUMERIC(8,2),
	
	CONSTRAINT PK_ITENSENTRADA PRIMARY KEY (ITENSENTRADAID),
	CONSTRAINT FK_ITENSENTRADA1 FOREIGN KEY (ENTRADAPRODUTOID) REFERENCES ENTRADAPRODUTO (ENTRADAPRODUTOID),
	CONSTRAINT FK_ITENSENTRADA2 FOREIGN KEY (PRODUTOID) REFERENCES PRODUTO (PRODUTOID)
);