CREATE SEQUENCE SEQ_FORNECEDOR;
CREATE TABLE FORNECEDOR (
	FORNECEDORID NUMERIC(20) NOT NULL,
	RAZAOSOCIAL VARCHAR(300),
	NOMEFANTASIA VARCHAR(300),
	CPF VARCHAR(11),
	CNPJ VARCHAR(14),
		
	CONSTRAINT PK_FORNECEDOR PRIMARY KEY (FORNECEDORID)
);