CREATE SEQUENCE SEQ_MOVIMENTACAO;
CREATE TABLE MOVIMENTACAOESTOQUE (
	MOVIMENTACAOESTOQUEID NUMERIC(20) NOT NULL,
	TIPO VARCHAR(20) NOT NULL,
	DATA DATE,
	FORNECEDORID NUMERIC(20),
	
		
	CONSTRAINT PK_MOVIMENTACAOESTOQUE PRIMARY KEY (MOVIMENTACAOESTOQUEID),
	CONSTRAINT FK_MOVIMENTACAOESTOQUE FOREIGN KEY (FORNECEDORID) REFERENCES FORNECEDOR (FORNECEDORID)
);