CREATE SEQUENCE SEQ_ITEMENTRADA;
CREATE TABLE ITEMENTRADA (
	ITEMENTRADAID NUMERIC(20) NOT NULL,
	MOVIMENTACAOESTOQUEID NUMERIC(20) NOT NULL,
	PRODUTOID NUMERIC(20),
	QUANTIDADE NUMERIC(8),
	VALORUNITARIO NUMERIC(8,2),
	TOTAL NUMERIC(8,2),
	
	
	CONSTRAINT PK_ITEMENTRADA PRIMARY KEY (ITEMENTRADAID),
	CONSTRAINT FK_ITEMENTRADA1 FOREIGN KEY (MOVIMENTACAOESTOQUEID) REFERENCES MOVIMENTACAOESTOQUE (MOVIMENTACAOESTOQUEID),
	CONSTRAINT FK_ITEMENTRADA2 FOREIGN KEY (PRODUTOID) REFERENCES PRODUTO (PRODUTOID)
);