CREATE SEQUENCE SEQ_UNIDADEDEMEDIDA;
CREATE TABLE UNIDADEDEMEDIDA (
	UNIDADEDEMEDIDAID NUMERIC(20) NOT NULL,
	NOME VARCHAR(300) NOT NULL,
	SITUACAO CHAR(3),
	CONSTRAINT PK_UNIDADEDEMEDIDA PRIMARY KEY (UNIDADEDEMEDIDAID)
);