CREATE SEQUENCE SEQ_SALDOESTOQUE;
CREATE TABLE SALDOESTOQUE (
	SALDOESTOQUEID NUMERIC(20) NOT NULL,
	LOCALARMAZENAMENTOID NUMERIC(20) NOT NULL,
	ITEMENTRADAID NUMERIC(20),
	RESTANTE NUMERIC(8),	
	CONSTRAINT PK_SALDOESTOQUE PRIMARY KEY (SALDOESTOQUEID),
	CONSTRAINT FK_SALDOESTOQUE1 FOREIGN KEY (LOCALARMAZENAMENTOID) REFERENCES LOCALARMAZENAMENTO (LOCALARMAZENAMENTOID),
	CONSTRAINT FK_SALDOESTOQUE2 FOREIGN KEY (ITEMENTRADAID) REFERENCES ITEMENTRADA (ITEMENTRADAID)
);