CREATE SEQUENCE SEQ_FORNECEDOR;
CREATE TABLE FORNECEDOR (
	FORNECEDORID NUMERIC(20) NOT NULL,
	MUNICIPIODOFORNECEDORID NUMERIC(20),
	RAZAOSOCIAL VARCHAR(300),
	NOMEFANTASIA VARCHAR(300),
	NUMERODOCUMENTO VARCHAR(14),
	CONSTRAINT PK_FORNECEDOR PRIMARY KEY (FORNECEDORID),
	CONSTRAINT FK_FORNECEDOR1 FOREIGN KEY (MUNICIPIODOFORNECEDORID) REFERENCES MUNICIPIO (MUNICIPIOID)
);